### ISSUE TITLE
Template for 404 was not found

### ISSUE THREAD

**Issue by runphp** [ApiGen/ThemeDefault#7]

**Comment by TomasVotruba** [comment]
Could you provide more details?

**Comment by runphp** [comment]
![4](https://cloud.githubusercontent.com/assets/1510812/7131073/0eb456f2-e2ad-11e4-99e2-ec61a9a73729.jpg)

I was install api-gen with composer

**Comment by TomasVotruba** [comment]
Could you run fresh installation, should be fixed now.
